[project]
name = "weather"
version = "0.1.0"
description = "MCP Weather Server"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta" 